### ISSUE TITLE
How to solve this?

### ISSUE THREAD

**Issue by coolwateRx3** [rzanca/bombcrypto-multibot#10]
I did everything as in the instruction and everything was well, except when i start the bot. It somehow does not work for me on google cloud server.

A lot of lines coming up in the cmd but nothing happens. Is this normal or do I need to configure something?
![grafik](https://user-images.githubusercontent.com/96804038/149590483-75ead350-bb21-413e-b811-5936b81771e5.png)

**Comment by rzanca** [comment]
I just uploaded an update, if possible test it and pass the feedback

**Comment by coolwateRx3** [comment]
Oki I will try. I also joined the telegram groups for a better communication.

Thank you a lot

**Comment by coolwateRx3** [comment]
Damn still the error. I deleted the old files and downloaded the new ones and put the token and ID into the config. Requirements were still there, nothing was updated. Can we have a chat on telegram maybe ? 
![grafik](https://user-images.githubusercontent.com/96804038/149593812-55144991-09d9-482a-b803-4d13192151e8.png)

**Comment by rzanca** [comment]
New update, you can try again.

**Comment by coolwateRx3** [comment]
wow you are legend. Works perfect.
Thank you a lot
