### ISSUE TITLE
Cadastro Telegram

### ISSUE THREAD

**Issue by Mytic-Slander** [rzanca/bombcrypto-multibot#11]
Não estou conseguindo, quando chega na parte de copiar o chatid, não aparece igual na imagem que está no tutorial. Aparece apenas isso:

![image](https://user-images.githubusercontent.com/83298605/149621716-7d1a6eba-1c0a-4bd2-842b-e1ae11171a9f.png)

![image](https://user-images.githubusercontent.com/83298605/149621739-666599c9-cb7a-4746-b82d-4749bdc948f7.png)

**Comment by rzanca** [comment]
Bom dia, confere o token api, se estiver correto. Reenvia a mensagem para o seu bot. E atualiza a página. 
Qualquer dúvida, tem o link do telegram no final do tutorial.

**Comment by Mytic-Slander** [comment]
> Bom dia, confere o token api, se estiver correto. Reenvia a mensagem para o seu bot. E atualiza a página. Qualquer dúvida, tem o link do telegram no final do tutorial.

Obrigado, funcionou ;)

**Comment by Raoniq** [comment]
Também passei por isso rsrs, valeu pela resposta
