### ISSUE TITLE
Problema se usar scroll_attempts: 4

### ISSUE THREAD

**Issue by Raoniq** [rzanca/bombcrypto-multibot#12]
Boa tarde, gostaria primeiro de agradecer pelo bot que parece funcionar muito bem (acabei de instalar), pretendo fazer doações recorrentes conforme for retirando bcoin.
Deixando os elogios de lado, reparei 1 problema somente.. Quando eu coloco scroll_attempts: 4 o bot deixa de ativar o último herói verde da lista de heróis e já volta pro treasure hunt. Talvez seja de vez em quando, não testei o suficiente e subi logo pra 5.

De qualquer forma não é nada que quebre o bot, só resolvi te avisar, valeu!

**Comment by rzanca** [comment]
Boa tarde, muito obrigado.
Quanto ao erro do scroll. Está variando conforme a máquina e resolução. Em alguns casos 3 ou 4 resolvem. Mas outros precisa usar 5. Acredito que até o próximo update vai estar corrigido.
