### ISSUE TITLE
Mensagem Telegram identificação do navegador

### ISSUE THREAD

**Issue by fumasa21** [rzanca/bombcrypto-multibot#13]
Olá! Parabéns pelo excelente trabalho, Bot esta perfeito!
Como podemos identificar cada janela do Chrome na msg do Telegram "Seu Saldo Bcoins em bombcrypto - Google Chome" 
Ex: 
"Seu Saldo Bcoins em bombcrypto - Conta 1"
"Seu Saldo Bcoins em bombcrypto - Conta 2"
doação em breve, merecida pela dedicação nos detalhes.

**Comment by rzanca** [comment]
> Olá! Parabéns pelo excelente trabalho, Bot esta perfeito! Como podemos identificar cada janela do Chrome na msg do Telegram "Seu Saldo Bcoins em bombcrypto - Google Chome" Ex: "Seu Saldo Bcoins em bombcrypto - Conta 1" "Seu Saldo Bcoins em bombcrypto - Conta 2" doação em breve, merecida pela dedicação nos detalhes.

Muito obrigado, até o momento isso é uma limitação do próprio Chrome, as soluções seriam:
- Usar o Microsoft Edge, além de mais leve e rápido, acaba mostrando o nome do perfil no título da janela. (Recomendado)
- Usar um software/extensão de terceiros para customizar o título da janela de cada Chrome. (Maior risco)
