### ISSUE TITLE
problema no metamask ao conectar

### ISSUE THREAD

**Issue by RonaldoPerini** [rzanca/bombcrypto-multibot#17]
quando demora mais de 8 segundos para aparecer o botao de connect no metamask ele ja clica na janela do Bomb.... como se fosse multi account e ai acaba que ele nao loga e nao consegue detectar a janela metamask ja aberta, o que eu poderia fazer?

**Comment by jaonetu** [comment]
so abrir o bot dps que conectar

**Comment by RonaldoPerini** [comment]
> so abrir o bot dps que conectar

???.... isso ja e o proprio bot reconectando, ele abre o metamask mas demora pra carregar a aba e ai acaba clicando na janela do Bomb... ignorando o metamask

**Comment by rzanca** [comment]
> quando demora mais de 8 segundos para aparecer o botao de connect no metamask ele ja clica na janela do Bomb.... como se fosse multi account e ai acaba que ele nao loga e nao consegue detectar a janela metamask ja aberta, o que eu poderia fazer?

Pode tentar aumentar o timeout da função de login, no arquivo index.py 
É preciso usar um editor de código (notepad++, sublime text) 
Mas já estamos trabalhando numa versão aprimorada para substituir a atual na parte de login.

**Comment by RonaldoPerini** [comment]
> Pode tentar aumentar o timeout da função de login, no arquivo index.py É preciso usar um editor de código (notepad++, sublime text) Mas já estamos trabalhando numa versão aprimorada para substituir a atual na parte de login.

eu tentei aumentar mas o que esta impedindo é a checagem de aba com nome bombcrypto... ai acaba que ele clica na aba e ignora o metamask... vou aguardar entao o seu update, agradeco!

**Comment by jaonetu** [comment]
> > so abrir o bot dps que conectar
> 
> ???.... isso ja e o proprio bot reconectando, ele abre o metamask mas demora pra carregar a aba e ai acaba clicando na janela do Bomb... ignorando o metamask

achei q era na hora de entrar a primeira vez, foi mal

**Comment by rzanca** [comment]
> > Pode tentar aumentar o timeout da função de login, no arquivo index.py É preciso usar um editor de código (notepad++, sublime text) Mas já estamos trabalhando numa versão aprimorada para substituir a atual na parte de login.
> 
> eu tentei aumentar mas o que esta impedindo é a checagem de aba com nome bombcrypto... ai acaba que ele clica na aba e ignora o metamask... vou aguardar entao o seu update, agradeco!

A checagem da aba, usa o alt+tab para fazer a troca, ele não está clicando na aba. Tem alguma coisa impedindo o login.

**Comment by RonaldoPerini** [comment]
> > > Pode tentar aumentar o timeout da função de login, no arquivo index.py É preciso usar um editor de código (notepad++, sublime text) Mas já estamos trabalhando numa versão aprimorada para substituir a atual na parte de login.
> > 
> > 
> > eu tentei aumentar mas o que esta impedindo é a checagem de aba com nome bombcrypto... ai acaba que ele clica na aba e ignora o metamask... vou aguardar entao o seu update, agradeco!
> 
> A checagem da aba, usa o alt+tab para fazer a troca, ele não está clicando na aba. Tem alguma coisa impedindo o login.

o metamask demora um pouco pra carregar e ai ele ja clica na aba do bomb, ai ignora o sing in 
![aa](https://user-images.githubusercontent.com/94665916/150535516-a23ddff6-5888-4f80-a38b-74dd4bb8d5a4.png)

**Comment by rzanca** [comment]
Verifica se resolveu com o novo update

**Comment by RonaldoPerini** [comment]
> Verifica se resolveu com o novo update

ainda nao amigo, se demora uns 10 segundos pra abrir o metamask ele meio que ignora a janela e ja vai pra do bomb... ai fica dessa forma sem conseguir conectar
![aao](https://user-images.githubusercontent.com/94665916/150700570-f2af1a3d-3fed-4ad1-8817-b91d1341d54e.png)
![aa21](https://user-images.githubusercontent.com/94665916/150700584-ea869f4a-6c34-40fa-ace4-f4858a231e46.png)

o problema acho que ta sendo na deteccao da janela do Bombcrypto pra multiaccounts... ai ele deve detectar que tem que selecionar dnv a aba e acaba ignorando o login do metamask

**Comment by rzanca** [comment]
Mais uns ajustes, deve resolver.

**Comment by RonaldoPerini** [comment]
> Mais uns ajustes, deve resolver.

vlw pela forca!!
