### ISSUE TITLE
rzanca janela metamask 

### ISSUE THREAD

**Issue by RonaldoPerini** [rzanca/bombcrypto-multibot#19]
@rzanca teria como adicionar opcao de apenas avancar depois que a janela metamask sumir? continuo tendo problemas com multi accounts no metamask, uma conta ainda ta no metamask se ela demora 1 pouco pra carregar ela ignora e clica na aba do bombcrypto ficando aberta... nao logando e demorando pra tentar o reloggin

**Comment by RonaldoPerini** [comment]
tipo se encontrar aba metamask navegation.... igual abas do bombcrypto

**Comment by rzanca** [comment]
Bom dia, fiz mais uma correção, vamos ver se agora resolve rsrs.

**Comment by RonaldoPerini** [comment]
> Bom dia, fiz mais uma correção, vamos ver se agora resolve rsrs.

Bom dia, muito obrigado pela ajuda amigo!, vou testar aqui

**Comment by RonaldoPerini** [comment]
> Bom dia, fiz mais uma correção, vamos ver se agora resolve rsrs.

obrg mano! rodando sem problemas agora
