### ISSUE TITLE
Add functionality click all to work

### ISSUE THREAD

**Issue by dmacobr** [rzanca/bombcrypto-multibot#2]
Can you add a functionality to click in add all and put The bombers to work?

**Comment by rzanca** [comment]
Actually the "Add All" button is not implemented, but if you have the necessity of send all the heroes to work, you can change the 'select_heros_mode' function in the 'config.yaml' file.
I can verified the possibility of made a new function for this button.

**Comment by rzanca** [comment]
The new functionality has just been implemented in version 0.3.3
You can change the 'select_heroes_mode' function in the 'config.yaml' file.
