### ISSUE TITLE
Telegram Error

### ISSUE THREAD

**Issue by AllanHBC** [rzanca/bombcrypto-multibot#4]
Opa, quando digito no endereço do navegador https://api.telegram.org/bot/getupdates ele retorna o seguinte:

{"ok":false,"error_code":404,"description":"Not Found"}

To comendo bola com algo?

**Comment by rzanca** [comment]
Você precisa incluir o token api, depois da palavra bot
Exemplo:
https://api.telegram.org/bot11111111111115adaddada/getupdates

**Comment by AllanHBC** [comment]
Ai que burro, ta escrito isso. Li com a bunda.

Vlw <3
