### ISSUE TITLE
Problema quando se tem muitas contas 

### ISSUE THREAD

**Issue by olivete** [rzanca/bombcrypto-multibot#5]
Olá! Primeiro, obrigado pelo bot. Estou rodando e tá muito bem feito. Adorei os detalhes, mouse mais rápido, movimento mais aleatório, msg pra o telegram :)

Descobri um problema quando você tem umas 6 contas ou mais.

Digamos que tu tem dez contas, o bot começa o loop e vai controlando cada conta. Supondo que a conta dez é a última, quando ele volta pra conta 1, no caso, a primeira conta, geralmente essa conta ficou afk e jogo kicka você com aquela mensagem de afk.

Aí vem o problema. Quando uma conta fica afk e bot reconecta ela, ele acessa o menu do jogo, volta pra tela do jogo, e daí pula pra próxima conta sem por ninguém pra trabalhar.

Se você tem 3 ou 4 contas, isso não é problema, o loop é curto, daí quando o bot volta nessa conta que reconectou, ainda dá tempo de por os heroes pra trabalhar.

Porém quando você tem muitas contas, o tempo que o bot leva pra voltar nessa conta que caiu e reconectou, é muito longo, aí ela fica afk de novo e o ciclo de repete.

Correcao seria: ao logar no jogo, ter certeza que botou boneco pra trabalhar, e isso ele faz, desde que seja o primeiro login do loop. Quando é uma reconexao, ele pula pra próxima conta sem por ninguém pra trabalhar.

**Comment by rzanca** [comment]
Bom dia amigo, muito obrigado. 
Estou reconstruindo todo o código do bot para uma versão mais estruturada e seguindo os padrões estabelecidos pelas PEPs, visto que a base desse bot foi inscrita pelo mbcapete. 
Esse processo vai levar um tempo e com certeza vai haver diversas mudanças nos recursos. 

Porém esse erro apresentado já vou verificar o que pode ser feito e subir um ajuste para corrigir, o controle das janelas tem um problema também ocasionado pelo uso dos navegadores chromium, que estão controlando o gerenciamento de energia e causando bugs no game.

Muito obrigado pelo feedback!

**Comment by olivete** [comment]
Valeu por responder!

Deixei teu bot durante a noite, deu muito certo. O único erro que vi foi esse que relatei. Para pessoas com muitas contas o loop é tão grande que quando ele termina, a primeira conta ja ficou afk e foi kickada. Dai ao reconectar a conta afk ele nunca poe pra trabalhar, ele conecta, mas passa pra proxima conta da fila.

De qualquer maneira, agradeço demais ai teu esforço, se conseguir esse fix vai ser mais show ainda :)

Em breve farei uma doação ai pra ti, obrigado por compartilhar!

**Comment by jeffersonveloso** [comment]
> Bom dia amigo, muito obrigado. Estou reconstruindo todo o código do bot para uma versão mais estruturada e seguindo os padrões estabelecidos pelas PEPs, visto que a base desse bot foi inscrita pelo mbcapete. Esse processo vai levar um tempo e com certeza vai haver diversas mudanças nos recursos.
> 
> Porém esse erro apresentado já vou verificar o que pode ser feito e subir um ajuste para corrigir, o controle das janelas tem um problema também ocasionado pelo uso dos navegadores chromium, que estão controlando o gerenciamento de energia e causando bugs no game.
> 
> Muito obrigado pelo feedback!

Cara eu trabalho com python, mais especificamente com o flask e nunca trabalhei com o pyautogui e gostaria de saber como pegar imagens do jogo para implementar algumas idéias que tenho e contribuir com este projeto. Você poderia me explicar como pegar as imagens ? A idéia é contribuir com o projeto para tentar maximizar nossos lucros no farm. Se você me der um ok até te passo meu zap e se for necessário pago pela orientação.

**Comment by rzanca** [comment]
> Valeu por responder!
> 
> Deixei teu bot durante a noite, deu muito certo. O único erro que vi foi esse que relatei. Para pessoas com muitas contas o loop é tão grande que quando ele termina, a primeira conta ja ficou afk e foi kickada. Dai ao reconectar a conta afk ele nunca poe pra trabalhar, ele conecta, mas passa pra proxima conta da fila.
> 
> De qualquer maneira, agradeço demais ai teu esforço, se conseguir esse fix vai ser mais show ainda :)
> 
> Em breve farei uma doação ai pra ti, obrigado por compartilhar!

Acabei de subir uma correção que ao identificar a reconexão, vai executar o comando dos heróis. Nos testes aqui ficou tudo 100%, está incluso na versão 0.4.0, além de uma melhoria no telegram.

**Comment by jeffersonveloso** [comment]
> > Valeu por responder!
> > Deixei teu bot durante a noite, deu muito certo. O único erro que vi foi esse que relatei. Para pessoas com muitas contas o loop é tão grande que quando ele termina, a primeira conta ja ficou afk e foi kickada. Dai ao reconectar a conta afk ele nunca poe pra trabalhar, ele conecta, mas passa pra proxima conta da fila.
> > De qualquer maneira, agradeço demais ai teu esforço, se conseguir esse fix vai ser mais show ainda :)
> > Em breve farei uma doação ai pra ti, obrigado por compartilhar!
> 
> Acabei de subir uma correção que ao identificar a reconexão, vai executar o comando dos heróis. Nos testes aqui ficou tudo 100%, está incluso na versão 0.4.0, além de uma melhoria no telegram.

Parabéns pelo projeto e por todo esforço por melhorias, depois dê uma olhada em minha mensagem acima.

**Comment by rzanca** [comment]
> > Bom dia amigo, muito obrigado. Estou reconstruindo todo o código do bot para uma versão mais estruturada e seguindo os padrões estabelecidos pelas PEPs, visto que a base desse bot foi inscrita pelo mbcapete. Esse processo vai levar um tempo e com certeza vai haver diversas mudanças nos recursos.
> > Porém esse erro apresentado já vou verificar o que pode ser feito e subir um ajuste para corrigir, o controle das janelas tem um problema também ocasionado pelo uso dos navegadores chromium, que estão controlando o gerenciamento de energia e causando bugs no game.
> > Muito obrigado pelo feedback!
> 
> Cara eu trabalho com python, mais especificamente com o flask e nunca trabalhei com o pyautogui e gostaria de saber como pegar imagens do jogo para implementar algumas idéias que tenho e contribuir com este projeto. Você poderia me explicar como pegar as imagens ? A idéia é contribuir com o projeto para tentar maximizar nossos lucros no farm. Se você me der um ok até te passo meu zap e se for necessário pago pela orientação.

Tem bastante conteúdo sobre o pyAutoGui, mas é basicamente ele que executa a maior parte das funções relacionadas a mouse, teclado e botões.
https://pyautogui.readthedocs.io/en/latest/

**Comment by jeffersonveloso** [comment]
> > > Bom dia amigo, muito obrigado. Estou reconstruindo todo o código do bot para uma versão mais estruturada e seguindo os padrões estabelecidos pelas PEPs, visto que a base desse bot foi inscrita pelo mbcapete. Esse processo vai levar um tempo e com certeza vai haver diversas mudanças nos recursos.
> > > Porém esse erro apresentado já vou verificar o que pode ser feito e subir um ajuste para corrigir, o controle das janelas tem um problema também ocasionado pelo uso dos navegadores chromium, que estão controlando o gerenciamento de energia e causando bugs no game.
> > > Muito obrigado pelo feedback!
> > 
> > 
> > Cara eu trabalho com python, mais especificamente com o flask e nunca trabalhei com o pyautogui e gostaria de saber como pegar imagens do jogo para implementar algumas idéias que tenho e contribuir com este projeto. Você poderia me explicar como pegar as imagens ? A idéia é contribuir com o projeto para tentar maximizar nossos lucros no farm. Se você me der um ok até te passo meu zap e se for necessário pago pela orientação.
> 
> Tem bastante conteúdo sobre o pyAutoGui, mas é basicamente ele que executa a maior parte das funções relacionadas a mouse, teclado e botões. https://pyautogui.readthedocs.io/en/latest/

As imagens do jogo você capturou com essa lib ou foi dando print mesmo e tentando formatar de uma melhor forma a ser identificada durante a execução ? Eu quero implementar uma forma de detectar no final dos maps se existe somente pedras no mapa e ai colocar meus heróis de raridade maior para descansar.

**Comment by rzanca** [comment]
> As imagens do jogo você capturou com essa lib ou foi dando print mesmo e tentando formatar de uma melhor forma a ser identificada durante a execução ? Eu quero implementar uma forma de detectar no final dos maps se existe somente pedras no mapa e ai colocar meus heróis de raridade maior para descansar.

No momento ele usa os prints como referência, busca uma imagem semelhante, e ai executa a função.

**Comment by olivete** [comment]
> > Valeu por responder!
> > Deixei teu bot durante a noite, deu muito certo. O único erro que vi foi esse que relatei. Para pessoas com muitas contas o loop é tão grande que quando ele termina, a primeira conta ja ficou afk e foi kickada. Dai ao reconectar a conta afk ele nunca poe pra trabalhar, ele conecta, mas passa pra proxima conta da fila.
> > De qualquer maneira, agradeço demais ai teu esforço, se conseguir esse fix vai ser mais show ainda :)
> > Em breve farei uma doação ai pra ti, obrigado por compartilhar!
> 
> Acabei de subir uma correção que ao identificar a reconexão, vai executar o comando dos heróis. Nos testes aqui ficou tudo 100%, está incluso na versão 0.4.0, além de uma melhoria no telegram.

Opa!!!!!!!!!!!!!! Passei o dia fora ontem dai nao tive chance de testar, vou tentar experimentar hoje e te mando o feedback. Valeu!!!

**Comment by kerferber** [comment]
Aproveitando o tópico.. o multiaccount funciona no linux?

**Comment by rzanca** [comment]
Não, está em testes, mas não tive tempo de finalizar o ajuste e subir a nova versão. Motivos pessoais. Assim que conseguir. Vou subir o multi plataformas.
