### ISSUE TITLE
Ideias de novas funções 

### ISSUE THREAD

**Issue by ftlag** [rzanca/bombcrypto-multibot#6]
Primeiramente parabéns, o bot está rodando liso e ficou muito boa a integração com o telegram.

Eu não sei se é possível, mas seria legal ver essas funções no bot:

* Converter a imagem do saldo em número e a cada 24h enviar uma mensagem com o saldo do dia.
* Enviar uma imagem da tela a cada X minutos, caso o jogo bugue, assim você já consegue voltar no acesso remoto e ajustar pra rodar de novo.

Um erro que tem acontecido aqui no meu, é que eu tô rodando duas contas, mas as vezes a tela fica toda branca e quando recarrega da erro de WebGL. Teria algum motivo? Estava dando no Firefox, troquei para o edge mas as vezes ainda acontece.

**Comment by rzanca** [comment]
> 



> Primeiramente parabéns, o bot está rodando liso e ficou muito boa a integração com o telegram.
> 
> Eu não sei se é possível, mas seria legal ver essas funções no bot:
> 
> * Converter a imagem do saldo em número e a cada 24h enviar uma mensagem com o saldo do dia.
> * Enviar uma imagem da tela a cada X minutos, caso o jogo bugue, assim você já consegue voltar no acesso remoto e ajustar pra rodar de novo.
> Um erro que tem acontecido aqui no meu, é que eu tô rodando duas contas, mas as vezes a tela fica toda branca e quando recarrega da erro de WebGL. Teria algum motivo? Estava dando no Firefox, troquei para o edge mas as vezes ainda acontece.

Muito obrigado, quanto as sugestões. 
Envio de imagens é tranquilo, agora quando falamos de envio de texto convertido, começam alguns problemas de execução do tessaract OCR, porque precisa ser instalado a parte na máquina e isso acaba trazendo alguns erros, a primeira versão do telegram usava texto, e retornava em muitos problemas. 
Se eu conseguir uma solução que funcione melhor, tenha certeza que vou colocar. 

Quanto a imagem da tela, na versão nova que estou reescrevendo, tem uma função que verifica e envia um texto de aviso, caso seja necessário intervenção manual. 

O erro de WebGL é do navegador, tenta limpar cache e verificar as configurações relacionadas a aceleração de hardware.

**Comment by ftlag** [comment]
Ah entendi, show de bola, com essa nova função aí da pra saber se precisa ir lá pra fazer alguma intervenção né. 

O erro será que tem a ver com o fato de eu estar rodando sem placa de video? Eu deixei a minha na minha mineradora, e o pc está rodando na placa onboard. Apesar da placa mãe ser boa acredito que a placa gráfica seja fraca.

**Comment by rzanca** [comment]
Normalmente ele retorna devido a falta de recursos. Pode ser que o sistema está trabalhando sobrecarregado

**Comment by ftlag** [comment]
O pior que meu PC que tá rodando é bom, só está sem a placa de vídeo. Mas de resto ele só fica com o navegador aberto.

**Comment by rzanca** [comment]
Desativa a Aceleração de Hardware que deve resolver.

**Comment by ftlag** [comment]
Ah vou testar aqui, valeu!! ;)

**Comment by ftlag** [comment]
O movimento do mouse ficou sensacional, mas quando ele clica nos ícones é sempre no mesmo spot, tem como fazer ele clicar em algum lugar aleatório da imagem? Se existir algum log de coordenadas onde clica aí ficaria mais "humano".

**Comment by rzanca** [comment]
Sugestão anotada e em desenvolvimento para posterior implementação.
