### ISSUE TITLE
Parou de funcionar

### ISSUE THREAD

**Issue by 8driano** [rzanca/bombcrypto-multibot#7]
Estava funcionando tudo normal até a ultima atualização que teve, ele fica abrindo infinitamente o baú pra mostrar o valor, não troca de aba e fica enviando notificação a cada minuto no telegram de que iniciei o bot

**Comment by rzanca** [comment]
Bom dia, consegue anexar uma foto do erro? Na linha de comando?

**Comment by rzanca** [comment]
Acabei de identificar esse erro e subi uma alteração que vai resolver. Só baixar novamente. Ou executar o comando pip install Pillow
