### ISSUE TITLE
Problemas ao executar no Linux ( ubuntu, debian)

### ISSUE THREAD

**Issue by petryck** [rzanca/bombcrypto-multibot#9]
Erro com PyGetWindow dei uma pesquisada e ele só é funcional no windows

**Comment by rzanca** [comment]
Se tiver usando em conta única essa versão resolve. https://github.com/rzanca/bombcrypto-bot

**Comment by petryck** [comment]
> Se tiver usando em conta única essa versão resolve. https://github.com/rzanca/bombcrypto-bot

Boa tarde, o objetivo de usar a versão que vc desenvolveu vou por ser varias contas kkk, mas de qualquer forma coloquei windows e foi de boa, vlw por ajudar a comunidade...

**Comment by rzanca** [comment]
Infelizmente a estrutura de algumas funções não permitem o uso de multi plataforma.
Por isso estou reescrevendo o bot do zero.
Quando tiver pronto vamos resolver muitos pedidos da comunidade

**Comment by matheusggds** [comment]
Linux pff ='(
